/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":base"))
    implementation("tools.jackson.core:jackson-databind:3.0.2")
    implementation("com.networknt:json-schema-validator:2.0.0")
    api(libs.net.bytebuddy.byte.buddy)
    api(libs.org.checkerframework.checker.qual)
    api(libs.org.slf4j.slf4j.api)
    api(libs.ch.qos.logback.logback.classic)
    testImplementation(project(":plugins-test-shared"))
    testImplementation(libs.com.google.jimfs.jimfs)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "Foomp-Plugins (Runtime)"

java {
    withJavadocJar()
}
