/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Foomp"
include(":plugins-test-implementation1")
include(":plugins")
include(":base")
include(":plugins-test-shared")
include(":automata")
include(":plugins-test-implementation2")
include(":higher")
include(":plugins-runtime")
project(":plugins-test-implementation1").projectDir = file("Plugins/Plugins-Test-Implementation1")
project(":plugins").projectDir = file("Plugins")
project(":base").projectDir = file("Base")
project(":plugins-test-shared").projectDir = file("Plugins/Plugins-Test-Shared")
project(":automata").projectDir = file("Automata")
project(":plugins-test-implementation2").projectDir = file("Plugins/Plugins-Test-Implementation2")
project(":higher").projectDir = file("Higher")
project(":plugins-runtime").projectDir = file("Plugins/Plugins-Runtime")
