/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":base"))
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.checkerframework.checker.qual)
    testImplementation(libs.org.slf4j.slf4j.api)
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

description = "Foomp-Automata"

java {
    withJavadocJar()
}
