/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.api.tasks.testing.Test
import org.gradle.testing.jacoco.tasks.JacocoReport
import org.gradle.api.tasks.javadoc.Javadoc
import org.gradle.external.javadoc.StandardJavadocDocletOptions
import org.gradle.api.tasks.SourceSetContainer

plugins {
    `java-library`
    jacoco
    `maven-publish`
}

repositories {
    mavenCentral()
    mavenLocal()
}

group = "org.quurz.foomp"
version = "0.1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_25
java.targetCompatibility = JavaVersion.VERSION_25

java {
    withSourcesJar()
}

jacoco {
    toolVersion = "0.8.13" // oder gewünschte Version
}

// Eigene Configuration für das UMLDoclet
val umlDoclet: Configuration by configurations.creating

// Gemeinsame Test-Konfiguration für alle Projekte, die dieses Plugin anwenden
dependencies {
    // JUnit 5 (Jupiter) – feste Version, nach Bedarf anpassen
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0")

    // WICHTIG: JUnit Platform Launcher
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.0")

    testImplementation("org.assertj:assertj-core:3.26.0")
    testImplementation("org.mockito:mockito-core:5.14.1")
    testImplementation("org.mockito:mockito-junit-jupiter:5.14.1")

    // UMLDoclet-Dependency für die umlDoclet-Configuration
    umlDoclet("nl.talsmasoftware:umldoclet:2.2.4")
}

// Alle Test-Tasks (z.B. :Automata:test) auf JUnit 5 konfigurieren
tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    testLogging {
        events("PASSED", "FAILED", "SKIPPED")
    }
    // Nach jedem Testlauf den Coverage-Report erzeugen
    finalizedBy("jacocoTestReport")
}

// Alle Jacoco-Report-Tasks konfigurieren (pro Projekt/Variante gibt es eine)
tasks.withType<JacocoReport>().configureEach {
    dependsOn("test") // Tests müssen vor dem Report laufen

    reports {
        xml.required.set(true)
        csv.required.set(false)
        html.required.set(true)
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

// Basis-Javadoc-Einstellungen
tasks.withType<Javadoc>().configureEach {
    options.encoding = "UTF-8"
    // TODO: Später wieder scharf schalten
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:none", "-quiet")
}

// UMLDoclet für alle Javadoc-Tasks verwenden
tasks.withType<Javadoc>().configureEach {
    val docletOptions = options as StandardJavadocDocletOptions

    source = project.extensions.getByType<SourceSetContainer>()["main"].allJava

    docletOptions.docletpath = umlDoclet.files.toList()
    docletOptions.doclet = "nl.talsmasoftware.umldoclet.UMLDoclet"

    // Optional: Ressourcen aus src/main/javadoc übernehmen
    val javadocResources = project.file("src/main/javadoc")
    if (javadocResources.exists()) {
        inputs.dir(javadocResources)
        doLast {
            copy {
                from(javadocResources)
                into(destinationDir!!)
            }
        }
    }
}
