/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    // Reicht i.d.R. völlig
    mavenCentral()
    mavenLocal()
}

group = "org.quurz.foomp"
version = "0.1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_25
java.targetCompatibility = JavaVersion.VERSION_25

java {
    withSourcesJar()
}

// Gemeinsame Test-Konfiguration für alle Projekte, die dieses Plugin anwenden
dependencies {
    // JUnit 5 (Jupiter) – feste Version, nach Bedarf anpassen
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0")

    // WICHTIG: JUnit Platform Launcher
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.0")

    testImplementation("org.assertj:assertj-core:3.26.0")
    testImplementation("org.mockito:mockito-core:5.14.1")
    testImplementation("org.mockito:mockito-junit-jupiter:5.14.1")
}

tasks.withType<Test> {
    // JUnit 5 aktivieren
    useJUnitPlatform()

    testLogging {
        events("PASSED", "FAILED", "SKIPPED")
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    // TODO: Später wieder scharf schalten
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:none", "-quiet")
}
